### ISSUE TITLE
DatabaseGptClient should be IDisposable

### ISSUE THREAD

**Issue by nicolaparo** [marcominerva/DatabaseGPT#22]
The current implementation of `DatabaseGptClient` creates in the constructor the instance for its own `IDatabaseGptProvider` according to the configuration set in the service initialization. Since all the implementations of `IDatabaseGptProvider` also implement the `IDisposable` interface in order to be disposed properly, also the interface `IDatabaseGptProvider` should implement it. As a consequence of this, it is appropriate that also `DatabaseGptClient` implements `IDisposable` in order to deallocate the resources that were created while instantiating the service.

**Comment by marcominerva** [comment]
@nicolaparo can you take care of this issue?
