### ISSUE TITLE
Missing call to the method ThrowIfDisposed()

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/DatabaseGPT#5]
I was watching the code and I noticed that in the SqlContext.cs object, there's a missing call to the ThrowIfDisposed method at line 37
Was in intentional or is it just missing?

**Comment by marcominerva** [comment]
Could you please add an hyperlink to the file you refer, so it is easy to identify it?

**Comment by marcominerva** [comment]
Yes, it is definitively missing. In this particular case it isn't a problem, because the `SqlContext` class is used via Dependency Injection, but it is better to add the call to `ThrowIfDisposed` also in this method. Do you mind to take care of this task making a PR?

**Comment by N1K0232** [comment]
Question. The "review required" is enabled in this repository? I don't want to cause troubles when making the PR

**Comment by N1K0232** [comment]
Thank you so much for giving me the chance to collaborate :)
