### ISSUE TITLE
What is the DefaultModel in appsettings.json?

### ISSUE THREAD

**Issue by djtyambao** [marcominerva/DatabaseGPT#74]
Hi I tried to run the application, but I am receiving an error that says "The model my-model does not exist or you do not have access to it."? 

Currently, the appsettings.json default value is set to ->  "DefaultModel": "my-model",
What setting do I need to assign in the DefaultModel?  I am using the Northwind Database as test data. 

Thank you,

Jake Crisostomo

**Comment by marcominerva** [comment]
You need to specify the configuration of your OpenAI model, like described at https://github.com/marcominerva/ChatGptNet?tab=readme-ov-file#configuration.

**Comment by djtyambao** [comment]
Thank you for the quick response?

I am getting undefined coming from the OpenAI. Is this the correct parameter in the appsettings?
**"DefaultModel": "o1-preview",**

**Comment by marcominerva** [comment]
It depends on your configuration and to which models you have access.
